Repository tgragnato/magnetico, pull requests merged in 2024-12, with the labels that each got.

#535 Add Pagination Functionality
  persistence/bitmagnet.go
  persistence/interface.go
  persistence/postgres.go
  persistence/postgres_test.go
  persistence/rabbitmq.go
  persistence/sqlite3.go
  persistence/sqlite3_test.go
  persistence/zeromq.go
  persistence/zeromq_mock.go
  web/router.go
  web/torrents.go
  web/torrents_test.go
Labels: enhancement, go

#536 Removes two debugging messages from statistics page
  web/static/scripts/statistics.js
Labels: bug, javascript

#537 fix(web): don't use HTML entities when building URL (12c79539 fix-up)
  web/feed.go
  web/torrent.go
Labels: bug, go

#541 improve the clarity of the `torrentstotal` semantics
  web/torrents.go
  web/torrents_test.go
Labels: refactoring, go
