Repository tgragnato/magnetico, pull requests merged in 2024-03, with the labels that each got.

#166 fix(makefile): missing tag during unit testing
  Makefile
Labels: bug, testing

#168 Use individual databses for each test
  persistence/sqlite3_test.go
Labels: bug, testing, go

#170 fix(mainline): randomize nodeID
  dht/mainline/indexingService.go
Labels: bug, go

#177 fix(mainline): Fix routingTable locking issue
  dht/mainline/indexingService.go
  dht/mainline/routingTable.go
  dht/mainline/routingTable_test.go
Labels: bug, go

#175 feat(mainline): allow user-supplied bootstrap nodes
  cmd/magneticod/main.go
  dht/mainline/indexingService.go
  dht/mainline/indexingService_test.go
  dht/managers.go
  dht/managers_test.go
Labels: enhancement, go
